/**
* api
* Imaginary API of a BME MobilLabor project based on https://api.chucknorris.io.
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.laki.mobillab.data.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param createdAt 
 * @param iconUrl 
 * @param id 
 * @param updatedAt 
 * @param url 
 * @param value 
 */
@JsonClass(generateAdapter = true)
data class JokeDTO (
    @Json(name = "created_at")
    val createdAt: kotlin.String,
    @Json(name = "icon_url")
    val iconUrl: kotlin.String,
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "updated_at")
    val updatedAt: kotlin.String,
    @Json(name = "url")
    val url: kotlin.String,
    @Json(name = "value")
    val value: kotlin.String
)

